name: Build production containers and deploy to vps

on:
  push:
    branches: [ "main" ]

jobs:
  install-nx:
    name: Install Nx
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build apps
      run: npm run build
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}

    - name: 'Build images'
      run: INPUT_GITHUB_TOKEN=${{ secrets.GIT_TOKEN }} npm run container

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [install-nx]
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/telegram-shop
            docker compose down
            docker compose build --pull --no-cache
            docker compose up -d
