name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  install-nx:
    name: Install Nx
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # build-coomand: ["shop-backend", "shop-frontend"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build apps
      run: npm run build
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}

    # - name: Build frontend
    #   run: ./node_modules/.bin/nx run shop-frontend:push-container

    - name: Build backend
      run: ./node_modules/.bin/nx run shop-backend:push-container
